spring:
  zipkin:
    base-url: http://localhost:9411
    # nacos不会将zipkin作为一个服务注册发现，只把它作为url对待
    discoveryClientEnabled: false
  sleuth:
    sampler:
      probability: 1.0 # zipkin从sleuth的信息采集率，0-1之间
